### PR TITLE
Modified a few questions that students stumbled on.

### PR DESCRIPTION
**Pull request by DanielNScott**
I'm suggesting some question tweaks based on my experience 
TA-ing the class at Brown. I have notes on each homework and will
finish going through them shortly. I think they should clarify some
things for students as well as save TAs a bit of repeating various
explanations in person and while grading.

Description:
Q2.2: The second part of this question can be hard to understand
if you don't recognize the dynamical importance of type II vs
type I neurons. Having noted the obvious qualitative diff,
some students think they're missing something and make stray
observations in response.

Q2.4: Some students were unclear what was being asked of them
with regards to the mathematical manipulation in 2.4.

Q3.1: The ordering language confused a lot of students, and many
would give "orderings" and explanations that were at odds.

Q3.3: The actual order of unit activation is not necessarily
the same as the order of correct unit activation, which is what
the question is really about. Students would thus report wrong
and or highly detailed info about transients rather than the main
thing.

### CODE REVIEW

**Comment by DanielNScott** [comment]
PS, sorry a handful of lines have stray white space changes. That might be a result of editing w/ VIM.

**Comment by rcoreilly** [comment]
@frankmj @DanielNScott Thanks for the changes.  I have wanted to avoid a / b kinds of sub-questions, just because that adds an additional level of complexity WRT grading, points etc.  It is much simpler to just have 1 point for each question.  And one of these new questions requires drawing a graph -- I typically have people submit on canvas electronically, so would like to avoid that.

Could you and Michael revise in light of these constraints?  Happy to discuss on our call tomorrow if needed..

**Comment by DanielNScott** [comment]
@rcoreilly That certainly makes sense, and was actually the reason I had wanted to break some of the questions down. There are cases where multiple literal questions are one assignment question e.g 3.3, and places where an assignment question such as 3.1 has multiple implicit questions while only one actual grammatical question. I found these difficult to grade when students would answer differing numbers of sub questions, be they implicitly or explicitly asked, or when students would give answers to different sub-questions that were at odds with one another other. I was thinking the a-b-c model would make things comply with a one question one answer format more plainly. What do you think, if anything, might be done? Maybe a solution is to just make them 3.1, 3.2, etc? Maybe to not ask multiple questions in one "question"? Or maybe just to let everyone grade and interpret however?

Re the graph thing, makes sense, I can just remove that from the request. For that one I was just trying to come up with a way to mitigate the conversation I had a bunch of times where students would say "It turns off... what important property am I missing?". Doesn't matter much though.

**Comment by rcoreilly** [comment]
I don't have a lot of time to fix this right now, so I'm biased to not change things -- I'm going to make a release now..   I'm just going to make the changes myself directly.  Here's some commentary:

* Q 2.2: I think the original is sufficiently unitary -- if you don't get the important aspect of neurons behavior then you haven't really answered the question at all.. 

* Q 2.4: made your changes.

* Q 3.1: incorporated some of your clarifications, but kept as one question -- second part is "specifically" so the answer must include this detail.

* Q 3.3: likewise, made it an "and* so it is clear that both parts must be specified for each answer.

overall I think this should fix most of the issues raised without changing number of points etc.

**Pull request closed without merging**
